### ISSUE TITLE
PCB Rev 2.0 [22]

### ISSUE THREAD

**Issue by suvratjain12** [Algias/RobotBasketball#78]
-Updated Schematic Design
-Major Updates on PCB Board
-Decreased PCB Size
-Added female connectors for IMU Sensor
-Fixed the parts list for the BOM 2.0
-Checked PCB against the Schematic
-Fixed the copper pours for GND plane
-Generated Gerbers
-Ordered PCB and Stencil

**Comment by Algias** [comment]
PCA9635 instead of PCA9685 was used on the board so that does not work. Everything else is fine. Using dev board in meantime
